spring:
  profiles:
        active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootdemo2
    username: root
    password: root

  application:
    name: productapp
server:
  port: 8090
PRODUCT_APP_ERROR_500: "pls try after some time"


key:
  message: "it is a default profile"

account:
  message: "welcome to productapp default profile"
  contactDetails:
    name: "raj default"
    email: "rgupta.default@gmail.com"
  onCallSupport:
    -054645464556
    -075765777677

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"