spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/propfiles
          clone-on-start: true
          default-label: master

  application:
    name: configserver
server:
  port: 8888