spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
      - dev
  application:
    name: app2
server:
  port: 8092

app:
  name: dev app2

management:
  endpoints:
    web:
      exposure:
        include: "*"