spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active:
      - dev
  application:
    name: app1
server:
  port: 8091

app:
  name: default config app1

management:
  endpoints:
    web:
      exposure:
        include: "*"
