apiVersion: v1
kind: Namespace
metadata:
  name: user-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment
  namespace: user-app
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-app-container
          image: ''
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191

---

apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: user-app
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9191
  type: NodePort
