apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: user-app
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9191
  type: NodePort