version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=root